services:
  engine:
    container_name: engine
    build:
      context: ./src/engine
      target: engine
    ports:
      - 5001:5000
  play-game:
    container_name: play-game
    build:
      context: ./src/play-game
      target: play-game
    ports:
      - 5002:5000
  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      target: frontend
    ports:
      - "3000:3000"
