services:
  engine:
    container_name: engine
    build:
      context: ./src/engine
      target: engine
    ports:
      - 5001:5000
  play-game:
    container_name: play-game
    build:
      context: ./src/play-game
      target: play-game
    ports:
      - 5002:5001
