services:

  engine:
    container_name: engine
    build:
      context: ./src
      target: engine
    ports:
      - 5001:5001

  play-game:
    container_name: play-game
    build:
      context: ./src
      target: play-game
    ports:
      - 5002:5001

  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      target: frontend
    ports:
      - "3000:3000"
      
  mongo:
    container_name: mongo
    build:
      context: ./src
      target: mongo
    ports:
      - "8000:8000"
    expose:
      - 8000

  cli:
    container_name: cli
    build:
      context: ./src
      target: cli
    stdin_open: true
    tty: true
    depends_on:
      - engine
      - play-game
