services:

  engine:
    container_name: engine
    build:
      context: ./src
      target: engine
    ports:
      - 5001:5001

  gateway:
    container_name: gateway
    build:
      context: ./src
      target: gateway
    ports:
      - 5002:5001

  frontend:
    container_name: frontend
    build:
      context: ./src
      target: frontend
    ports:
      - "3000:3000"
      
  mongo:
    container_name: mongo
    build:
      context: ./src
      target: mongo
    ports:
      - "8000:8000"
    expose:
      - 8000

  cli:
    container_name: cli
    build:
      context: ./src
      target: cli
    stdin_open: true
    tty: true
    depends_on:
      - engine
      - gateway

  auth:
    container_name: auth
    build:
      context: ./src
      target: auth
    ports:
      - "80:8000"
  stats:
    container_name: stats
    build:
      context: ./src
      target: stats
    ports:
      - 5003:5001
