services:

  engine:
    container_name: engine
    build:
      context: ./src
      target: engine
    ports:
      - 5001:5001
    depends_on:
      - mongo

  play-game:
    container_name: play-game
    build:
      context: ./src
      target: play-game
    ports:
      - 5002:5001
    depends_on:
      - engine

  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      target: frontend
    ports:
      - "3000:3000"
    depends_on:
      - play-game
      
  mongo:
    container_name: mongo
    build:
      context: ./src
      target: mongo
    expose:
      - 5000

  cli:
    container_name: cli
    build:
      context: ./src/cli
      target: cli
    stdin_open: true
    tty: true
    depends_on:
      - play-game
