services:
  engine:
    container_name: engine
    build:
      context: .
      target: engine
    ports:
      - 5001:5000
  play-game:
    container_name: play-game
    build:
      context: .
      target: play-game
    ports:
      - 5002:5000
  cli:
    container_name: cli
    build:
      context: ./src/cli
      target: cli
    stdin_open: true
    tty: true
    depends_on:
      - engine
      - play-game