services:
  engine:
    container_name: engine
    build:
      context: ./src/engine
      target: engine
    ports:
      - 5001:5000
  play-game:
    container_name: play-game
    build:
      context: ./src/play-game
      target: play-game
    ports:
      - 5002:5001
  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      target: frontend
    ports:
      - "3000:3000"
  cli:
    container_name: cli
    build:
      context: ./src/cli
      target: cli
    stdin_open: true
    tty: true
    depends_on:
      - engine
      - play-game
