services:
  engine:
    container_name: engine
    build:
      context: .
      target: engine
    ports:
      - 5001:5000
  play-game:
    container_name: play-game
    build:
      context: .
      target: play-game
    ports:
      - 5002:5000
  mongo:
    image: mongo:latest
    container_name: database
    build:
      context: .
      target: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: vaas1
    #   MONGO_INITDB_ROOT_PASSWORD: pass
